### ISSUE TITLE
[Feature Request] Builders that have a .setExecute() like SlashCommandBuilder

### ISSUE THREAD

**Issue by PAdventures** [thenorthsolution/Reciple#43]
E.g.
```ts
new ButtonBuilder()
    //blah blah
    .setExecute(async ({ interaction }) => {
        // blah blah
    })
```
There will be some nice checks done already, e.g. we won't **need** to check the custom id

**Comment by NotGhex** [comment]
Seems imposible since button, selectmenu and modals are not command interactions, so they need to rely on custom Ids to identify which component is which. On the other hand if made possible this will require reciple to scan every components of messages sent by the bot with a downside of higher memory usage additional complexity on code.

Alternatively using something like [reciple-interaction-events](https://www.npmjs.com/package/reciple-interaction-events) would help make handling components easier.
